-- 테이블 삭제
DROP TABLE IF EXISTS `ROUTINE_SCHEDULE`;
DROP TABLE IF EXISTS `ROUTINE`;
DROP TABLE IF EXISTS `ROUTINE_PRESET`;
DROP TABLE IF EXISTS `INTEREST_CATEGORY`;
DROP TABLE IF EXISTS `BADGE`;
DROP TABLE IF EXISTS `CATEGORY`;
DROP TABLE IF EXISTS `MEMBER_BADGE`;
DROP TABLE IF EXISTS `MEMBER_QUEST`;
DROP TABLE IF EXISTS `NOTIFICATION`;
DROP TABLE IF EXISTS `MEMBER_POINT`;
DROP TABLE IF EXISTS `ITEM`;
DROP TABLE IF EXISTS `MEMBER_ITEM`;
DROP TABLE IF EXISTS `POINT_LOG`;
DROP TABLE IF EXISTS `LOGIN_LOG`;
DROP TABLE IF EXISTS `WITHDRAW_REASON`;
DROP TABLE IF EXISTS `EVENT_QUEST`;
DROP TABLE IF EXISTS `WEEKLY_QUEST`;
DROP TABLE IF EXISTS `POINT_POLICY`;
DROP TABLE IF EXISTS `MEMBER_IMAGE`;
DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `INTEREST_CATEGORY` (
	`id`	LONG	NOT NULL,
	`category_id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `ROUTINE_SCHEDULE` (
	`id`	LONG	NOT NULL,
	`routine_id`	LONG	NOT NULL,
	`date`	DATE	NULL,
	`is_done`	BOOLEAN	NULL,
	`created_at`	TIMESTAMP	NULL
);

CREATE TABLE `MEMBER_QUEST` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`reference_key`	VARCHAR(50)	NULL,
	`id_done`	BOOLEAN	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_activate`	BOOLEAN	NULL
);

CREATE TABLE `MEMBER_IMAGE` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`save_path`	VARCHAR(50)	NULL,
	`type`	VARCHAR(36)	NULL,
	`origin_name`	VARCHAR(255)	NULL,
	`renamed_name`	VARCHAR(255)	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL,
	`Field`	VARCHAR(255)	NULL
);

CREATE TABLE `MEMBER_ITEM` (
	`id`	LONG	NOT NULL,
	`item_id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`is_equipped`	BOOLEAN	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `POINT_LOG` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`type`	VARCHAR(50)	NULL,
	`point`	INT	NULL,
	`reason`	VARCHAR(255)	NULL,
	`time`	TIMESTAMP	NULL
);

CREATE TABLE `ROUTINE` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`category_id`	LONG	NOT NULL,
	`content`	VARCHAR(255)	NULL,
	`trigger_time`	VARCHAR(255)	NULL,
	`is_important`	BOOLEAN	NULL,
	`repeat_type`	VARCHAR(20)	NULL,
	`repeat_value`	VARCHAR(100)	NULL,
	`is_active`	BOOLEAN	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

CREATE TABLE `CATEGORY` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`parent_id`	INT	NULL,
	`name`	VARCHAR(25)	NULL,
	`type`	VARCHAR(50)	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `MEMBER_POINT` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`point`	INT	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `MEMBER` (
	`id`	LONG	NOT NULL,
	`role`	VARCHAR(20)	NULL,
	`email`	VARCHAR(50)	NOT NULL,
	`password`	VARCHAR(255)	NULL,
	`name`	VARCHAR(10)	NULL,
	`nickname`	VARCHAR(50)	NULL,
	`residenceExperience`	VARCHAR(20)	NULL,
	`region_1dept`	VARCHAR(50)	NULL,
	`region_2dept`	VARCHAR(50)	NULL,
	`region_3dept`	VARCHAR(50)	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `WITHDRAW_REASON` (
	`id`	LONG	NOT NULL,
	`type`	VARCHAR(50)	NULL,
	`reason`	TEXT	NULL,
	`created_at`	TIMESTAMP	NULL
);

CREATE TABLE `NOTIFICATION` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`email`	BOOLEAN	NULL,
	`routine`	BOOLEAN	NULL,
	`challenge`	BOOLEAN	NULL
);

CREATE TABLE `WEEKLY_QUEST` (
	`id`	LONG	NOT NULL,
	`key`	VARCHAR(50)	NULL,
	`name`	VARCHAR(255)	NULL,
	`info`	TEXT	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `EVENT_QUEST` (
	`id`	LONG	NOT NULL,
	`key`	VARCHAR(50)	NULL,
	`name`	VARCHAR(255)	NULL,
	`info`	TEXT	NULL,
	`start_date`	TIMESTAMP	NULL,
	`end_date`	TIMESTAMP	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `MEMBER_BADGE` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`badge_id`	LONG	NOT NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `LOGIN_LOG` (
	`id`	LONG	NOT NULL,
	`member_id`	LONG	NOT NULL,
	`time`	TIMESTAMP	NULL
);

CREATE TABLE `POINT_POLICY` (
	`id`	LONG	NOT NULL,
	`type`	VARCHAR(50)	NULL,
	`reference_key`	VARCHAR(50)	NULL,
	`point`	INT	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `ITEM` (
	`id`	LONG	NOT NULL,
	`item_key`	VARCHAR(50)	NULL,
	`name`	VARCHAR(50)	NULL,
	`price`	INT	NULL,
	`type`	VARCHAR(50)	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

CREATE TABLE `ROUTINE_PRESET` (
	`id`	LONG	NOT NULL,
	`category_id`	LONG	NOT NULL,
	`content`	VARCHAR(50)	NULL,
	`is_active`	BOOLEAN	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL
);

CREATE TABLE `BADGE` (
	`id`	LONG	NOT NULL,
	`category_id`	LONG	NOT NULL,
	`key`	VARCHAR(50)	NULL,
	`name`	VARCHAR(100)	NULL,
	`tier`	VARCHAR(20) (nullable)	NULL,
	`how`	VARCHAR(100)	NULL,
	`requirement`	INT	NULL,
	`info`	VARCHAR(100)	NULL,
	`created_at`	TIMESTAMP	NULL,
	`updated_at`	TIMESTAMP	NULL,
	`is_active`	BOOLEAN	NULL
);

ALTER TABLE `INTEREST_CATEGORY` ADD CONSTRAINT `PK_INTEREST_CATEGORY` PRIMARY KEY (
	`id`
);

ALTER TABLE `ROUTINE_SCHEDULE` ADD CONSTRAINT `PK_ROUTINE_SCHEDULE` PRIMARY KEY (
	`id`
);

ALTER TABLE `MEMBER_QUEST` ADD CONSTRAINT `PK_MEMBER_QUEST` PRIMARY KEY (
	`id`
);

ALTER TABLE `MEMBER_IMAGE` ADD CONSTRAINT `PK_MEMBER_IMAGE` PRIMARY KEY (
	`id`
);

ALTER TABLE `MEMBER_ITEM` ADD CONSTRAINT `PK_MEMBER_ITEM` PRIMARY KEY (
	`id`
);

ALTER TABLE `POINT_LOG` ADD CONSTRAINT `PK_POINT_LOG` PRIMARY KEY (
	`id`
);

ALTER TABLE `ROUTINE` ADD CONSTRAINT `PK_ROUTINE` PRIMARY KEY (
	`id`
);

ALTER TABLE `CATEGORY` ADD CONSTRAINT `PK_CATEGORY` PRIMARY KEY (
	`id`
);

ALTER TABLE `MEMBER_POINT` ADD CONSTRAINT `PK_MEMBER_POINT` PRIMARY KEY (
	`id`
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`id`
);

ALTER TABLE `WITHDRAW_REASON` ADD CONSTRAINT `PK_WITHDRAW_REASON` PRIMARY KEY (
	`id`
);

ALTER TABLE `NOTIFICATION` ADD CONSTRAINT `PK_NOTIFICATION` PRIMARY KEY (
	`id`
);

ALTER TABLE `WEEKLY_QUEST` ADD CONSTRAINT `PK_WEEKLY_QUEST` PRIMARY KEY (
	`id`
);

ALTER TABLE `EVENT_QUEST` ADD CONSTRAINT `PK_EVENT_QUEST` PRIMARY KEY (
	`id`
);

ALTER TABLE `MEMBER_BADGE` ADD CONSTRAINT `PK_MEMBER_BADGE` PRIMARY KEY (
	`id`
);

ALTER TABLE `LOGIN_LOG` ADD CONSTRAINT `PK_LOGIN_LOG` PRIMARY KEY (
	`id`
);

ALTER TABLE `POINT_POLICY` ADD CONSTRAINT `PK_POINT_POLICY` PRIMARY KEY (
	`id`
);

ALTER TABLE `ITEM` ADD CONSTRAINT `PK_ITEM` PRIMARY KEY (
	`id`
);

ALTER TABLE `ROUTINE_PRESET` ADD CONSTRAINT `PK_ROUTINE_PRESET` PRIMARY KEY (
	`id`
);

ALTER TABLE `BADGE` ADD CONSTRAINT `PK_BADGE` PRIMARY KEY (
	`id`
);

